openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0
components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        email_address:
          type: string
        user_password:
          type: string
      required:
        - username
        - email_address
        - user_password
